// Manual type aliases — not generated by Supabase (no DB enums defined).
// These are used across services/ and must stay in sync with column constraints.
export type ProfileStatus = 'normal' | 'warned' | 'flagged_cheater';
export type CompletionStatus = 'active' | 'under_review' | 'removed';
export type FriendRequestStatus = 'pending' | 'accepted' | 'rejected';
export type GroupRole = 'owner' | 'admin' | 'member';
export type QuestSourceType = 'official' | 'group' | 'spontaneous';
export type SpontaneousReviewStatus = 'pending_catalog' | 'promoted' | 'rejected';
export type AuraScope = 'official' | 'group';
export type AchievementVisibility = 'public' | 'friends' | 'group' | 'private';
export type GroupQuestStatus =
  | 'draft'
  | 'active'
  | 'archived'
  | 'submitted_for_review'
  | 'approved_as_official'
  | 'rejected';
export type ChallengeStatus = 'active' | 'completed' | 'cancelled';
export type ChallengeScoringMode = 'official_only' | 'group_only' | 'mixed';
export type QuestCreationRule = 'anyone' | 'admin_only' | 'admin_approval';
export type UserPlan = 'free' | 'pro';
export type ReportReason =
  | 'fake_proof'
  | 'stolen_image'
  | 'harassment'
  | 'dangerous_content'
  | 'spam';
export type ReportStatus = 'pending' | 'reviewed' | 'resolved' | 'dismissed';
export type NotificationType =
  | 'friend_request'
  | 'comment'
  | 'respect'
  | 'weekly_quest'
  | 'group_invite';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      blocked_users: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
          id: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
          id?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocked_users_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocked_users_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      challenge_scores: {
        Row: {
          challenge_id: string
          id: string
          score: number
          updated_at: string
          user_id: string
        }
        Insert: {
          challenge_id: string
          id?: string
          score?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          challenge_id?: string
          id?: string
          score?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "challenge_scores_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "group_challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "challenge_scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      comment_reactions: {
        Row: {
          comment_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          comment_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          comment_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comment_reactions_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comment_reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          completion_id: string
          content: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          completion_id: string
          content: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          completion_id?: string
          content?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comments_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "feed_completions_enriched"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "quest_completions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      completion_participants: {
        Row: {
          completion_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          completion_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          completion_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "completion_participants_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "feed_completions_enriched"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_participants_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "quest_completions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "completion_participants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      friend_requests: {
        Row: {
          created_at: string
          id: string
          receiver_id: string
          sender_id: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          receiver_id: string
          sender_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          receiver_id?: string
          sender_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "friend_requests_receiver_id_fkey"
            columns: ["receiver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friend_requests_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      friendships: {
        Row: {
          created_at: string
          id: string
          user_a_id: string
          user_b_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          user_a_id: string
          user_b_id: string
        }
        Update: {
          created_at?: string
          id?: string
          user_a_id?: string
          user_b_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "friendships_user_a_id_fkey"
            columns: ["user_a_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_user_b_id_fkey"
            columns: ["user_b_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      group_challenges: {
        Row: {
          created_at: string
          creator_id: string
          description: string | null
          end_date: string
          group_id: string
          id: string
          prize_description: string | null
          scoring_mode: string
          start_date: string
          status: string
          title: string
        }
        Insert: {
          created_at?: string
          creator_id: string
          description?: string | null
          end_date: string
          group_id: string
          id?: string
          prize_description?: string | null
          scoring_mode?: string
          start_date: string
          status?: string
          title: string
        }
        Update: {
          created_at?: string
          creator_id?: string
          description?: string | null
          end_date?: string
          group_id?: string
          id?: string
          prize_description?: string | null
          scoring_mode?: string
          start_date?: string
          status?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_challenges_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_challenges_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_invites: {
        Row: {
          created_at: string
          group_id: string
          id: string
          invitee_id: string
          inviter_id: string
          status: string
        }
        Insert: {
          created_at?: string
          group_id: string
          id?: string
          invitee_id: string
          inviter_id: string
          status?: string
        }
        Update: {
          created_at?: string
          group_id?: string
          id?: string
          invitee_id?: string
          inviter_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_invites_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_invites_invitee_id_fkey"
            columns: ["invitee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_invites_inviter_id_fkey"
            columns: ["inviter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      group_member_scores: {
        Row: {
          group_id: string
          id: string
          total_group_aura: number
          updated_at: string
          user_id: string
        }
        Insert: {
          group_id: string
          id?: string
          total_group_aura?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          group_id?: string
          id?: string
          total_group_aura?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_member_scores_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_member_scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      group_members: {
        Row: {
          group_id: string
          id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          group_id: string
          id?: string
          joined_at?: string
          role: string
          user_id: string
        }
        Update: {
          group_id?: string
          id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      group_quests: {
        Row: {
          aura_reward: number
          category: string | null
          created_at: string
          creator_id: string
          description: string | null
          group_id: string
          id: string
          image_url: string | null
          max_completions_per_user: number | null
          proof_type: string
          repeat_interval: string | null
          repeatability_type: string
          status: string
          title: string
          visibility: string
        }
        Insert: {
          aura_reward?: number
          category?: string | null
          created_at?: string
          creator_id: string
          description?: string | null
          group_id: string
          id?: string
          image_url?: string | null
          max_completions_per_user?: number | null
          proof_type?: string
          repeat_interval?: string | null
          repeatability_type?: string
          status?: string
          title: string
          visibility?: string
        }
        Update: {
          aura_reward?: number
          category?: string | null
          created_at?: string
          creator_id?: string
          description?: string | null
          group_id?: string
          id?: string
          image_url?: string | null
          max_completions_per_user?: number | null
          proof_type?: string
          repeat_interval?: string | null
          repeatability_type?: string
          status?: string
          title?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_quests_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_quests_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      group_settings: {
        Row: {
          created_at: string
          group_id: string
          id: string
          is_public: boolean
          quest_creation_rule: string
        }
        Insert: {
          created_at?: string
          group_id: string
          id?: string
          is_public?: boolean
          quest_creation_rule?: string
        }
        Update: {
          created_at?: string
          group_id?: string
          id?: string
          is_public?: boolean
          quest_creation_rule?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_settings_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: true
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          avatar_url: string | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "groups_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "groups_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          data: Json | null
          id: string
          is_read: boolean
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          data?: Json | null
          id?: string
          is_read?: boolean
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          data?: Json | null
          id?: string
          is_read?: boolean
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          activity_styles: string[]
          avatar_url: string | null
          bio: string | null
          city: string | null
          created_at: string
          date_of_birth: string | null
          display_name: string
          id: string
          is_admin: boolean
          onboarding_completed: boolean
          plan: string
          preferred_categories: string[]
          preferred_language: string
          status: string
          total_aura: number
          updated_at: string
          username: string
          yearly_aura: number
        }
        Insert: {
          activity_styles?: string[]
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string
          date_of_birth?: string | null
          display_name: string
          id: string
          is_admin?: boolean
          onboarding_completed?: boolean
          plan?: string
          preferred_categories?: string[]
          preferred_language?: string
          status?: string
          total_aura?: number
          updated_at?: string
          username: string
          yearly_aura?: number
        }
        Update: {
          activity_styles?: string[]
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string
          date_of_birth?: string | null
          display_name?: string
          id?: string
          is_admin?: boolean
          onboarding_completed?: boolean
          plan?: string
          preferred_categories?: string[]
          preferred_language?: string
          status?: string
          total_aura?: number
          updated_at?: string
          username?: string
          yearly_aura?: number
        }
        Relationships: []
      }
      quest_completions: {
        Row: {
          aura_earned: number
          aura_scope: string
          caption: string | null
          challenge_id: string | null
          completed_at: string
          created_at: string
          group_id: string | null
          group_quest_id: string | null
          id: string
          quest_id: string | null
          quest_source_type: string
          rating: number | null
          status: string
          user_id: string
          visibility: string
        }
        Insert: {
          aura_earned?: number
          aura_scope?: string
          caption?: string | null
          challenge_id?: string | null
          completed_at?: string
          created_at?: string
          group_id?: string | null
          group_quest_id?: string | null
          id?: string
          quest_id?: string | null
          quest_source_type?: string
          rating?: number | null
          status?: string
          user_id: string
          visibility?: string
        }
        Update: {
          aura_earned?: number
          aura_scope?: string
          caption?: string | null
          challenge_id?: string | null
          completed_at?: string
          created_at?: string
          group_id?: string | null
          group_quest_id?: string | null
          id?: string
          quest_id?: string | null
          quest_source_type?: string
          rating?: number | null
          status?: string
          user_id?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "quest_completions_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "group_challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_group_quest_id_fkey"
            columns: ["group_quest_id"]
            isOneToOne: false
            referencedRelation: "group_quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_media: {
        Row: {
          completion_id: string
          created_at: string
          id: string
          media_type: string
          media_url: string
          order_index: number
        }
        Insert: {
          completion_id: string
          created_at?: string
          id?: string
          media_type: string
          media_url: string
          order_index?: number
        }
        Update: {
          completion_id?: string
          created_at?: string
          id?: string
          media_type?: string
          media_url?: string
          order_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "quest_media_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "feed_completions_enriched"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_media_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "quest_completions"
            referencedColumns: ["id"]
          },
        ]
      }
      quest_suggestions: {
        Row: {
          created_at: string
          description: string | null
          id: string
          title: string
          user_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          title: string
          user_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quest_suggestions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quests: {
        Row: {
          aura_reward: number
          category: string
          cost_range: string
          created_at: string
          created_by: string | null
          description_en: string
          description_es: string
          difficulty: string
          id: string
          is_active: boolean
          is_spontaneous: boolean
          location_type: string
          max_completions_per_user: number | null
          proof_type: string
          repeat_interval: string | null
          repeatability_type: string
          spontaneous_review_status: string | null
          title_en: string
          title_es: string
        }
        Insert: {
          aura_reward: number
          category: string
          cost_range?: string
          created_at?: string
          created_by?: string | null
          description_en: string
          description_es: string
          difficulty: string
          id?: string
          is_active?: boolean
          is_spontaneous?: boolean
          location_type?: string
          max_completions_per_user?: number | null
          proof_type?: string
          repeat_interval?: string | null
          repeatability_type: string
          spontaneous_review_status?: string | null
          title_en: string
          title_es: string
        }
        Update: {
          aura_reward?: number
          category?: string
          cost_range?: string
          created_at?: string
          created_by?: string | null
          description_en?: string
          description_es?: string
          difficulty?: string
          id?: string
          is_active?: boolean
          is_spontaneous?: boolean
          location_type?: string
          max_completions_per_user?: number | null
          proof_type?: string
          repeat_interval?: string | null
          repeatability_type?: string
          spontaneous_review_status?: string | null
          title_en?: string
          title_es?: string
        }
        Relationships: [
          {
            foreignKeyName: "quests_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          completion_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          completion_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          completion_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "feed_completions_enriched"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "quest_completions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          comment_id: string | null
          completion_id: string | null
          created_at: string
          description: string | null
          id: string
          reason: string
          reported_user_id: string | null
          reporter_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
        }
        Insert: {
          comment_id?: string | null
          completion_id?: string | null
          created_at?: string
          description?: string | null
          id?: string
          reason: string
          reported_user_id?: string | null
          reporter_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Update: {
          comment_id?: string | null
          completion_id?: string | null
          created_at?: string
          description?: string | null
          id?: string
          reason?: string
          reported_user_id?: string | null
          reporter_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "feed_completions_enriched"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_completion_id_fkey"
            columns: ["completion_id"]
            isOneToOne: false
            referencedRelation: "quest_completions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_user_id_fkey"
            columns: ["reported_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_quests: {
        Row: {
          created_at: string
          id: string
          quest_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          quest_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          quest_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_quests_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_quests_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      feed_completions_enriched: {
        Row: {
          aura_earned: number | null
          aura_scope: string | null
          caption: string | null
          challenge_id: string | null
          completed_at: string | null
          created_at: string | null
          group_id: string | null
          group_name: string | null
          group_quest_id: string | null
          group_quest_title: string | null
          id: string | null
          media: Json | null
          media_count: number | null
          media_type: string | null
          media_url: string | null
          profile_avatar_url: string | null
          profile_display_name: string | null
          profile_username: string | null
          quest_aura_reward: number | null
          quest_category: string | null
          quest_difficulty: string | null
          quest_id: string | null
          quest_source_type: string | null
          quest_title_en: string | null
          quest_title_es: string | null
          rating: number | null
          status: string | null
          user_id: string | null
          visibility: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quest_completions_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "group_challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_group_quest_id_fkey"
            columns: ["group_quest_id"]
            isOneToOne: false
            referencedRelation: "group_quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_quest_id_fkey"
            columns: ["quest_id"]
            isOneToOne: false
            referencedRelation: "quests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quest_completions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      can_view_completion: {
        Args: {
          p_group_id: string
          p_owner_id: string
          p_quest_source_type: string
          p_status: string
          p_viewer_id: string
          p_visibility: string
        }
        Returns: boolean
      }
      completion_counts_for_challenge: {
        Args: {
          p_aura_scope: string
          p_challenge_id: string
          p_group_id: string
        }
        Returns: boolean
      }
      delete_current_user: { Args: never; Returns: undefined }
      fetch_comments_ranked: {
        Args: { p_completion_id: string; p_limit?: number; p_offset?: number }
        Returns: {
          completion_id: string
          content: string
          created_at: string
          id: string
          like_count: number
          user_id: string
        }[]
      }
      fetch_public_groups: {
        Args: { p_limit?: number; p_offset?: number; p_search?: string }
        Returns: {
          avatar_url: string
          created_at: string
          description: string
          id: string
          member_count: number
          name: string
          owner_avatar_url: string
          owner_display_name: string
          owner_id: string
          owner_username: string
        }[]
      }
      is_group_admin: {
        Args: { p_group_id: string; p_user_id: string }
        Returns: boolean
      }
      is_group_member: {
        Args: { p_group_id: string; p_user_id: string }
        Returns: boolean
      }
      leaderboard_global_page: {
        Args: { p_limit: number; p_offset: number; p_since: string }
        Returns: {
          avatar_url: string
          display_name: string
          id: string
          period_aura: number
          total_aura: number
          username: string
          yearly_aura: number
        }[]
      }
      transfer_group_ownership: {
        Args: { p_group_id: string; p_new_owner_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
